let msg = 'Leave me alone';
console.log(msg.toUpperCase());
console.log(msg.toLowerCase());
let msg_space = '    Leave me alone   ';
console.log(msg_space.trim());
console.log("haha weel soon".indexOf("s"));
let str = 'Welcome and happy new year';
str.slice(2,5);
str.replace('Welcome', 'Merry Christmas');
'Happy birthday to you '.repeat(2);
